i18n:
  availableLanguages:
    - fr
    - en
  defaultLang: fr
pages:
  defaultPage: home
additionals:
  folders:
    - baseDir: src
      path: common/php
    - baseDir: src
      path: common/js
      downloadable: true
  files:
    - baseDir: src
      path: favicon.ico
      downloadable: true
