serve:
  port: 8901
i18n:
  availableLanguages:
    - fr
    - en
  defaultLang: fr
pages:
  defaultPage: home
additionals:
  folders:
    - baseDir: src
      path: common/php
  files:
    - baseDir: src
      path: favicon.ico
      downloadable: true
